### ISSUE TITLE
Things about CS2113 ip peer evaluation

### ISSUE THREAD

**Issue by SibingWu** [trishaangelica/duke#5]
Hello @trishaangelica ,

I am one of the students whose CS2113 iP project will be evaluated by you via wk 8 survey:)

Since I just noticed that my released jar file cannot be compiled on JDK11, I update a new one. Please kindly take a look at the new version if the previous jar file did not work.

Thank you so much!

**Comment by SibingWu** [comment]
If you find everything works well or anything goes wrong, could you please kindly let me know? Thank you so much!

**Comment by trishaangelica** [comment]
Hello @SibingWu! SFLR! Yup no worries I reviewed your iP based on the updated JAR file and I could run it perfectly fine 😃
